// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
//
// PIPE lane mapper 反馈复位子模块。
// 每条 lane 的 phy_rst_n 接它当前 owner 的 ctrl_rst_n。
// 复用 onehot_mux 的极性归一化：sel_tgt 全 0（交接窗口，
// 无 owner）时安全态是保持复位（0），而不是悬空或维持上一个 owner。
import pipe_pkg::*;

module pipe_lane_rst_top #(
    parameter int LANE_COUNT = 16,
    parameter int NUM_CTRL   = 4
) (
    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,
    input  lane_sel_t              sel_tgt,
    output logic [LANE_COUNT-1:0] phy_rst_n
);

    assign phy_rst_n[0] = ctrl_rst_n[0];  // G0 直连 Ctrl0
    assign phy_rst_n[1] = ctrl_rst_n[0];  // G0 直连 Ctrl0
    assign phy_rst_n[2] = ctrl_rst_n[0];  // G0 直连 Ctrl0
    assign phy_rst_n[3] = ctrl_rst_n[0];  // G0 直连 Ctrl0
    // G1 lane4~7: Ctrl0, Ctrl1
    logic rst_n_g1;
    onehot_mux #(.WIDTH(1), .N(2), .SAFE(1'b0)) u_rst_g1 (
        .sel  (sel_tgt.g1),
        .din  ({ctrl_rst_n[1], ctrl_rst_n[0]}),
        .dout (rst_n_g1)
    );
    assign phy_rst_n[4] = rst_n_g1;
    assign phy_rst_n[5] = rst_n_g1;
    assign phy_rst_n[6] = rst_n_g1;
    assign phy_rst_n[7] = rst_n_g1;
    // G2 lane8~11: Ctrl0, Ctrl2
    logic rst_n_g2;
    onehot_mux #(.WIDTH(1), .N(2), .SAFE(1'b0)) u_rst_g2 (
        .sel  (sel_tgt.g2),
        .din  ({ctrl_rst_n[2], ctrl_rst_n[0]}),
        .dout (rst_n_g2)
    );
    assign phy_rst_n[8] = rst_n_g2;
    assign phy_rst_n[9] = rst_n_g2;
    assign phy_rst_n[10] = rst_n_g2;
    assign phy_rst_n[11] = rst_n_g2;
    // G3 lane12~15: Ctrl0, Ctrl2, Ctrl3
    logic rst_n_g3;
    onehot_mux #(.WIDTH(1), .N(3), .SAFE(1'b0)) u_rst_g3 (
        .sel  (sel_tgt.g3),
        .din  ({ctrl_rst_n[3], ctrl_rst_n[2], ctrl_rst_n[0]}),
        .dout (rst_n_g3)
    );
    assign phy_rst_n[12] = rst_n_g3;
    assign phy_rst_n[13] = rst_n_g3;
    assign phy_rst_n[14] = rst_n_g3;
    assign phy_rst_n[15] = rst_n_g3;

endmodule
