// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
//
// PIPE lane mapper MAC->PHY 数据 mux。
// onehot_mux 内部做极性归一化，sel 全 0 时输出 SAFE_M2P。
import pipe_pkg::*;

module pipe_lane_data_m2p #(
    parameter int LANE_COUNT = 16
) (
    input  lane_sel_t              sel_tgt,
    output mac2phy_lane_t [LANE_COUNT-1:0] phy_mac2phy,
    input  mac2phy_lane_t [15:0] ctrl0_mac2phy,
    input  mac2phy_lane_t [3:0] ctrl1_mac2phy,
    input  mac2phy_lane_t [7:0] ctrl2_mac2phy,
    input  mac2phy_lane_t [3:0] ctrl3_mac2phy
);

    assign phy_mac2phy[0] = ctrl0_mac2phy[0];  // 直连
    assign phy_mac2phy[1] = ctrl0_mac2phy[1];  // 直连
    assign phy_mac2phy[2] = ctrl0_mac2phy[2];  // 直连
    assign phy_mac2phy[3] = ctrl0_mac2phy[3];  // 直连
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l4 (
        .sel  (sel_tgt.g1),
        .din  ({ctrl1_mac2phy[0], ctrl0_mac2phy[4]}),
        .dout (phy_mac2phy[4])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l5 (
        .sel  (sel_tgt.g1),
        .din  ({ctrl1_mac2phy[1], ctrl0_mac2phy[5]}),
        .dout (phy_mac2phy[5])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l6 (
        .sel  (sel_tgt.g1),
        .din  ({ctrl1_mac2phy[2], ctrl0_mac2phy[6]}),
        .dout (phy_mac2phy[6])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l7 (
        .sel  (sel_tgt.g1),
        .din  ({ctrl1_mac2phy[3], ctrl0_mac2phy[7]}),
        .dout (phy_mac2phy[7])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l8 (
        .sel  (sel_tgt.g2),
        .din  ({ctrl2_mac2phy[0], ctrl0_mac2phy[8]}),
        .dout (phy_mac2phy[8])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l9 (
        .sel  (sel_tgt.g2),
        .din  ({ctrl2_mac2phy[1], ctrl0_mac2phy[9]}),
        .dout (phy_mac2phy[9])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l10 (
        .sel  (sel_tgt.g2),
        .din  ({ctrl2_mac2phy[2], ctrl0_mac2phy[10]}),
        .dout (phy_mac2phy[10])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(2), .SAFE(SAFE_M2P)) u_m2p_l11 (
        .sel  (sel_tgt.g2),
        .din  ({ctrl2_mac2phy[3], ctrl0_mac2phy[11]}),
        .dout (phy_mac2phy[11])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(3), .SAFE(SAFE_M2P)) u_m2p_l12 (
        .sel  (sel_tgt.g3),
        .din  ({ctrl3_mac2phy[0], ctrl2_mac2phy[4], ctrl0_mac2phy[12]}),
        .dout (phy_mac2phy[12])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(3), .SAFE(SAFE_M2P)) u_m2p_l13 (
        .sel  (sel_tgt.g3),
        .din  ({ctrl3_mac2phy[1], ctrl2_mac2phy[5], ctrl0_mac2phy[13]}),
        .dout (phy_mac2phy[13])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(3), .SAFE(SAFE_M2P)) u_m2p_l14 (
        .sel  (sel_tgt.g3),
        .din  ({ctrl3_mac2phy[2], ctrl2_mac2phy[6], ctrl0_mac2phy[14]}),
        .dout (phy_mac2phy[14])
    );
    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), .N(3), .SAFE(SAFE_M2P)) u_m2p_l15 (
        .sel  (sel_tgt.g3),
        .din  ({ctrl3_mac2phy[3], ctrl2_mac2phy[7], ctrl0_mac2phy[15]}),
        .dout (phy_mac2phy[15])
    );

endmodule
