// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
//
// PIPE lane mapper PHY->MAC 数据 mux（按 controller 端口汇聚）。
// sel_tgt 的互斥性由 sel_sync 保证。未被驱动的端口 tie 安全态。
import pipe_pkg::*;

module pipe_lane_data_p2m #(
    parameter int LANE_COUNT = 16
) (
    input  lane_sel_t              sel_tgt,
    input  phy2mac_lane_t [LANE_COUNT-1:0] phy_phy2mac,
    output phy2mac_lane_t [15:0] ctrl0_phy2mac,
    output phy2mac_lane_t [3:0] ctrl1_phy2mac,
    output phy2mac_lane_t [7:0] ctrl2_phy2mac,
    output phy2mac_lane_t [3:0] ctrl3_phy2mac
);

    // Ctrl0 x16
    assign ctrl0_phy2mac[0] = phy_phy2mac[0];  // 直连 lane0
    assign ctrl0_phy2mac[1] = phy_phy2mac[1];  // 直连 lane1
    assign ctrl0_phy2mac[2] = phy_phy2mac[2];  // 直连 lane2
    assign ctrl0_phy2mac[3] = phy_phy2mac[3];  // 直连 lane3
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_4 (
        .sel  (sel_tgt.g1),
        .din  ({SAFE_P2M, phy_phy2mac[4]}),
        .dout (ctrl0_phy2mac[4])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_5 (
        .sel  (sel_tgt.g1),
        .din  ({SAFE_P2M, phy_phy2mac[5]}),
        .dout (ctrl0_phy2mac[5])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_6 (
        .sel  (sel_tgt.g1),
        .din  ({SAFE_P2M, phy_phy2mac[6]}),
        .dout (ctrl0_phy2mac[6])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_7 (
        .sel  (sel_tgt.g1),
        .din  ({SAFE_P2M, phy_phy2mac[7]}),
        .dout (ctrl0_phy2mac[7])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_8 (
        .sel  (sel_tgt.g2),
        .din  ({SAFE_P2M, phy_phy2mac[8]}),
        .dout (ctrl0_phy2mac[8])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_9 (
        .sel  (sel_tgt.g2),
        .din  ({SAFE_P2M, phy_phy2mac[9]}),
        .dout (ctrl0_phy2mac[9])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_10 (
        .sel  (sel_tgt.g2),
        .din  ({SAFE_P2M, phy_phy2mac[10]}),
        .dout (ctrl0_phy2mac[10])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl0_11 (
        .sel  (sel_tgt.g2),
        .din  ({SAFE_P2M, phy_phy2mac[11]}),
        .dout (ctrl0_phy2mac[11])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl0_12 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, SAFE_P2M, phy_phy2mac[12]}),
        .dout (ctrl0_phy2mac[12])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl0_13 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, SAFE_P2M, phy_phy2mac[13]}),
        .dout (ctrl0_phy2mac[13])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl0_14 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, SAFE_P2M, phy_phy2mac[14]}),
        .dout (ctrl0_phy2mac[14])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl0_15 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, SAFE_P2M, phy_phy2mac[15]}),
        .dout (ctrl0_phy2mac[15])
    );

    // Ctrl1 x4
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl1_0 (
        .sel  (sel_tgt.g1),
        .din  ({phy_phy2mac[4], SAFE_P2M}),
        .dout (ctrl1_phy2mac[0])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl1_1 (
        .sel  (sel_tgt.g1),
        .din  ({phy_phy2mac[5], SAFE_P2M}),
        .dout (ctrl1_phy2mac[1])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl1_2 (
        .sel  (sel_tgt.g1),
        .din  ({phy_phy2mac[6], SAFE_P2M}),
        .dout (ctrl1_phy2mac[2])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl1_3 (
        .sel  (sel_tgt.g1),
        .din  ({phy_phy2mac[7], SAFE_P2M}),
        .dout (ctrl1_phy2mac[3])
    );

    // Ctrl2 x8
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl2_0 (
        .sel  (sel_tgt.g2),
        .din  ({phy_phy2mac[8], SAFE_P2M}),
        .dout (ctrl2_phy2mac[0])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl2_1 (
        .sel  (sel_tgt.g2),
        .din  ({phy_phy2mac[9], SAFE_P2M}),
        .dout (ctrl2_phy2mac[1])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl2_2 (
        .sel  (sel_tgt.g2),
        .din  ({phy_phy2mac[10], SAFE_P2M}),
        .dout (ctrl2_phy2mac[2])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(2), .SAFE(SAFE_P2M)) u_p2m_ctrl2_3 (
        .sel  (sel_tgt.g2),
        .din  ({phy_phy2mac[11], SAFE_P2M}),
        .dout (ctrl2_phy2mac[3])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl2_4 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, phy_phy2mac[12], SAFE_P2M}),
        .dout (ctrl2_phy2mac[4])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl2_5 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, phy_phy2mac[13], SAFE_P2M}),
        .dout (ctrl2_phy2mac[5])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl2_6 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, phy_phy2mac[14], SAFE_P2M}),
        .dout (ctrl2_phy2mac[6])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl2_7 (
        .sel  (sel_tgt.g3),
        .din  ({SAFE_P2M, phy_phy2mac[15], SAFE_P2M}),
        .dout (ctrl2_phy2mac[7])
    );

    // Ctrl3 x4
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl3_0 (
        .sel  (sel_tgt.g3),
        .din  ({phy_phy2mac[12], SAFE_P2M, SAFE_P2M}),
        .dout (ctrl3_phy2mac[0])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl3_1 (
        .sel  (sel_tgt.g3),
        .din  ({phy_phy2mac[13], SAFE_P2M, SAFE_P2M}),
        .dout (ctrl3_phy2mac[1])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl3_2 (
        .sel  (sel_tgt.g3),
        .din  ({phy_phy2mac[14], SAFE_P2M, SAFE_P2M}),
        .dout (ctrl3_phy2mac[2])
    );
    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), .N(3), .SAFE(SAFE_P2M)) u_p2m_ctrl3_3 (
        .sel  (sel_tgt.g3),
        .din  ({phy_phy2mac[15], SAFE_P2M, SAFE_P2M}),
        .dout (ctrl3_phy2mac[3])
    );

endmodule
