// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
//
// PIPE lane mapper 顶层。
//
// 纯例化层：时钟/BBM 在 pipe_lane_clk_top，
// MAC->PHY 数据 mux 在 pipe_lane_data_m2p，
// PHY->MAC 数据 mux 在 pipe_lane_data_p2m。
//
// lane 分组：归属序列相同的 lane 自动成组，共享一个 BBM。
//
//   G0 lane0~3        Ctrl0 / Ctrl0 / Ctrl0 / Ctrl0 直连
//   G1 lane4~7        Ctrl0 / Ctrl0 / Ctrl0 / Ctrl1 2 选 1 BBM
//   G2 lane8~11       Ctrl0 / Ctrl2 / Ctrl2 / Ctrl2 2 选 1 BBM
//   G3 lane12~15      Ctrl0 / Ctrl2 / Ctrl3 / Ctrl3 3 选 1 BBM
import pipe_pkg::*;

module pipe_lane_mapper_top #(
    parameter int NUM_MODES  = 4,
    parameter int LANE_COUNT = 16,
    parameter int NUM_CTRL   = 4
) (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic [LANE_COUNT-1:0] phy_pclk_out,
    /* verilator lint_on UNUSEDSIGNAL */
    input  logic                  test_en,
    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,   // 每 controller 一根，外部已同步
    input  logic [$clog2(NUM_MODES)-1:0] mode,

    output logic [NUM_CTRL-1:0]   ctrl_pclk,
    output logic [LANE_COUNT-1:0] phy_pclk_in,
    output logic [LANE_COUNT-1:0] phy_rst_n,

    // PHY 侧 PIPE 数据
    output mac2phy_lane_t [LANE_COUNT-1:0] phy_mac2phy,
    input  phy2mac_lane_t [LANE_COUNT-1:0] phy_phy2mac,

    // Controller 侧，各自真实宽度
    // Ctrl0 x16
    input  mac2phy_lane_t [15:0] ctrl0_mac2phy,
    output phy2mac_lane_t [15:0] ctrl0_phy2mac,
    // Ctrl1 x4
    input  mac2phy_lane_t [3:0] ctrl1_mac2phy,
    output phy2mac_lane_t [3:0] ctrl1_phy2mac,
    // Ctrl2 x8
    input  mac2phy_lane_t [7:0] ctrl2_mac2phy,
    output phy2mac_lane_t [7:0] ctrl2_phy2mac,
    // Ctrl3 x4
    input  mac2phy_lane_t [3:0] ctrl3_mac2phy,
    output phy2mac_lane_t [3:0] ctrl3_phy2mac
);

    lane_sel_t sel_tgt;   // 各 group 当前实际生效的 owner 选择

    //------------------------------------------------------------
    // 时钟子模块：ctrl_pclk 生成 + group sel_sync + 反馈时钟 mux
    //------------------------------------------------------------
    pipe_lane_clk_top #(
        .NUM_MODES  (NUM_MODES),
        .LANE_COUNT (LANE_COUNT),
        .NUM_CTRL   (NUM_CTRL)
    ) u_clk_top (
        .phy_pclk_out (phy_pclk_out),
        .test_en      (test_en),
        .mode         (mode),
        .ctrl_rst_n   (ctrl_rst_n),
        .ctrl_pclk    (ctrl_pclk),
        .phy_pclk_in  (phy_pclk_in),
        .sel_tgt      (sel_tgt)
    );

    //------------------------------------------------------------
    // 反馈复位子模块：phy_rst_n 按当前 owner 选 ctrl_rst_n
    //------------------------------------------------------------
    pipe_lane_rst_top #(
        .LANE_COUNT (LANE_COUNT),
        .NUM_CTRL   (NUM_CTRL)
    ) u_rst_top (
        .ctrl_rst_n (ctrl_rst_n),
        .sel_tgt    (sel_tgt),
        .phy_rst_n  (phy_rst_n)
    );

    //------------------------------------------------------------
    // MAC->PHY 数据 mux
    //------------------------------------------------------------
    pipe_lane_data_m2p #(
        .LANE_COUNT (LANE_COUNT)
    ) u_data_m2p (
        .sel_tgt      (sel_tgt),
        .phy_mac2phy  (phy_mac2phy),
        .ctrl0_mac2phy (ctrl0_mac2phy),
        .ctrl1_mac2phy (ctrl1_mac2phy),
        .ctrl2_mac2phy (ctrl2_mac2phy),
        .ctrl3_mac2phy (ctrl3_mac2phy)
    );

    //------------------------------------------------------------
    // PHY->MAC 数据 mux
    //------------------------------------------------------------
    pipe_lane_data_p2m #(
        .LANE_COUNT (LANE_COUNT)
    ) u_data_p2m (
        .sel_tgt      (sel_tgt),
        .phy_phy2mac  (phy_phy2mac),
        .ctrl0_phy2mac (ctrl0_phy2mac),
        .ctrl1_phy2mac (ctrl1_phy2mac),
        .ctrl2_phy2mac (ctrl2_phy2mac),
        .ctrl3_phy2mac (ctrl3_phy2mac)
    );

endmodule
