// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
//
// mode 译码：产生各 lane group 的目标 owner，以及各 controller
// 的目标 pclk 来源。纯组合，无状态。
//
// 输出直接进 BBM 的 tgt 端口，由 BBM 完成跨域同步与互锁。
import pipe_pkg::*;

module pipe_lane_decoder #(
    parameter int NUM_MODES = 4,
    /* verilator lint_off UNUSEDPARAM */
    parameter int NUM_CTRL  = 4   // 候选多于一个的 controller 才用到
    /* verilator lint_on UNUSEDPARAM */
) (
    input  logic [$clog2(NUM_MODES)-1:0] mode,
    output lane_sel_t sel_tgt
);

    always_comb begin
        sel_tgt = '0;

        unique case (mode)
            0: begin
                sel_tgt.g1 = 2'b01;  // Ctrl0
                sel_tgt.g2 = 2'b01;  // Ctrl0
                sel_tgt.g3 = 3'b001;  // Ctrl0
            end
            1: begin
                sel_tgt.g1 = 2'b01;  // Ctrl0
                sel_tgt.g2 = 2'b10;  // Ctrl2
                sel_tgt.g3 = 3'b010;  // Ctrl2
            end
            2: begin
                sel_tgt.g1 = 2'b01;  // Ctrl0
                sel_tgt.g2 = 2'b10;  // Ctrl2
                sel_tgt.g3 = 3'b100;  // Ctrl3
            end
            3: begin
                sel_tgt.g1 = 2'b10;  // Ctrl1
                sel_tgt.g2 = 2'b10;  // Ctrl2
                sel_tgt.g3 = 3'b100;  // Ctrl3
            end
            default: begin
                sel_tgt = '0;
            end
        endcase
    end

endmodule
