// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
//
// PIPE lane mapper 时钟子模块。
// 包含：controller pclk 生成、group sel_sync、反馈时钟 mux。
// group 的 sel_sync 模式: comb (SYNC=0, 组合直通，要求候选 controller 共用同一时钟域)
// 反馈复位 mux 在 pipe_lane_rst_top，数据 mux 在
// pipe_lane_data_m2p / pipe_lane_data_p2m 中。
import pipe_pkg::*;

module pipe_lane_clk_top #(
    parameter int NUM_MODES  = 4,
    parameter int LANE_COUNT = 16,
    parameter int NUM_CTRL   = 4
) (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic [LANE_COUNT-1:0] phy_pclk_out,
    /* verilator lint_on UNUSEDSIGNAL */
    input  logic                  test_en,
    input  logic [$clog2(NUM_MODES)-1:0] mode,

    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,

    output logic [NUM_CTRL-1:0]   ctrl_pclk,
    output logic [LANE_COUNT-1:0] phy_pclk_in,
    output lane_sel_t              sel_tgt   // 各 group 当前实际生效的 owner 选择
);

    lane_sel_t dec_tgt;   // 译码器的原始目标，本模块内部用，不对外暴露

    pipe_lane_decoder #(
        .NUM_MODES (NUM_MODES),
        .NUM_CTRL  (NUM_CTRL)
    ) u_decoder (
        .mode     (mode),
        .sel_tgt  (dec_tgt)
    );

    //------------------------------------------------------------
    // controller pclk：固定取组内最低编号 lane 的 phy_pclk。
    // 候选多于一个的才需要无毛刺切换。
    //------------------------------------------------------------
    // Ctrl0: 所有 mode 都用 phy_pclk[0]，直连
    assign ctrl_pclk[0] = phy_pclk_out[0];

    // Ctrl1: 所有 mode 都用 phy_pclk[4]，直连
    assign ctrl_pclk[1] = phy_pclk_out[4];

    // Ctrl2: 所有 mode 都用 phy_pclk[8]，直连
    assign ctrl_pclk[2] = phy_pclk_out[8];

    // Ctrl3: 所有 mode 都用 phy_pclk[12]，直连
    assign ctrl_pclk[3] = phy_pclk_out[12];

    //------------------------------------------------------------
    // 每个非直连 group 一个 sel_sync（SYNC=1'b0）。
    //------------------------------------------------------------
    // G1 lane4~7: Ctrl0, Ctrl1
    sel_sync #(.N(2), .SYNC(1'b0)) u_sel_sync_g1 (
        .branch_clk   ({ctrl_pclk[1], ctrl_pclk[0]}),
        .branch_rst_n ({ctrl_rst_n[1], ctrl_rst_n[0]}),
        .tgt          (dec_tgt.g1),
        .en           (sel_tgt.g1)
    );

    // G2 lane8~11: Ctrl0, Ctrl2
    sel_sync #(.N(2), .SYNC(1'b0)) u_sel_sync_g2 (
        .branch_clk   ({ctrl_pclk[2], ctrl_pclk[0]}),
        .branch_rst_n ({ctrl_rst_n[2], ctrl_rst_n[0]}),
        .tgt          (dec_tgt.g2),
        .en           (sel_tgt.g2)
    );

    // G3 lane12~15: Ctrl0, Ctrl2, Ctrl3
    sel_sync #(.N(3), .SYNC(1'b0)) u_sel_sync_g3 (
        .branch_clk   ({ctrl_pclk[3], ctrl_pclk[2], ctrl_pclk[0]}),
        .branch_rst_n ({ctrl_rst_n[3], ctrl_rst_n[2], ctrl_rst_n[0]}),
        .tgt          (dec_tgt.g3),
        .en           (sel_tgt.g3)
    );

    //------------------------------------------------------------
    // 反馈时钟：每条 lane 的 pclk_in 接它当前 owner 的 ctrl_pclk。
    // 与数据共用同一组 en，保证数据与时钟同步切换。
    //------------------------------------------------------------
    assign phy_pclk_in[0] = ctrl_pclk[0];  // G0 直连 Ctrl0
    assign phy_pclk_in[1] = ctrl_pclk[0];  // G0 直连 Ctrl0
    assign phy_pclk_in[2] = ctrl_pclk[0];  // G0 直连 Ctrl0
    assign phy_pclk_in[3] = ctrl_pclk[0];  // G0 直连 Ctrl0
    // G1 lane4~7: Ctrl0, Ctrl1
    logic [1:0] pin_gated_g1;
    logic pclk_in_g1;
    clk_gate u_pin_gate_g1_b0 (.clk_in(ctrl_pclk[0]), .en(sel_tgt.g1[0]), .test_en(test_en), .clk_out(pin_gated_g1[0]));
    clk_gate u_pin_gate_g1_b1 (.clk_in(ctrl_pclk[1]), .en(sel_tgt.g1[1]), .test_en(test_en), .clk_out(pin_gated_g1[1]));
    assign pclk_in_g1 = |pin_gated_g1;
    assign phy_pclk_in[4] = pclk_in_g1;
    assign phy_pclk_in[5] = pclk_in_g1;
    assign phy_pclk_in[6] = pclk_in_g1;
    assign phy_pclk_in[7] = pclk_in_g1;
    // G2 lane8~11: Ctrl0, Ctrl2
    logic [1:0] pin_gated_g2;
    logic pclk_in_g2;
    clk_gate u_pin_gate_g2_b0 (.clk_in(ctrl_pclk[0]), .en(sel_tgt.g2[0]), .test_en(test_en), .clk_out(pin_gated_g2[0]));
    clk_gate u_pin_gate_g2_b1 (.clk_in(ctrl_pclk[2]), .en(sel_tgt.g2[1]), .test_en(test_en), .clk_out(pin_gated_g2[1]));
    assign pclk_in_g2 = |pin_gated_g2;
    assign phy_pclk_in[8] = pclk_in_g2;
    assign phy_pclk_in[9] = pclk_in_g2;
    assign phy_pclk_in[10] = pclk_in_g2;
    assign phy_pclk_in[11] = pclk_in_g2;
    // G3 lane12~15: Ctrl0, Ctrl2, Ctrl3
    logic [2:0] pin_gated_g3;
    logic pclk_in_g3;
    clk_gate u_pin_gate_g3_b0 (.clk_in(ctrl_pclk[0]), .en(sel_tgt.g3[0]), .test_en(test_en), .clk_out(pin_gated_g3[0]));
    clk_gate u_pin_gate_g3_b1 (.clk_in(ctrl_pclk[2]), .en(sel_tgt.g3[1]), .test_en(test_en), .clk_out(pin_gated_g3[1]));
    clk_gate u_pin_gate_g3_b2 (.clk_in(ctrl_pclk[3]), .en(sel_tgt.g3[2]), .test_en(test_en), .clk_out(pin_gated_g3[2]));
    assign pclk_in_g3 = |pin_gated_g3;
    assign phy_pclk_in[12] = pclk_in_g3;
    assign phy_pclk_in[13] = pclk_in_g3;
    assign phy_pclk_in[14] = pclk_in_g3;
    assign phy_pclk_in[15] = pclk_in_g3;

endmodule
