#!/usr/bin/env python3
"""
PIPE Lane Mapper RTL 生成器。

只生成配置相关的部分：类型定义、mode 译码、以及 common 模块的例化与接线。
BBM、同步器、时钟门控、one-hot mux 都是 rtl/common 下的手写模块，不随配置变。
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plm_config import load          # noqa: E402

BANNER = "// Auto-generated by tools/plm_gen.py -- DO NOT EDIT"


# ---------------------------------------------------------------- 类型包

def gen_pkg(cfg):
    L = [BANNER, "package pipe_pkg;", ""]

    for d, tname in (("mac2phy", "mac2phy_lane_t"), ("phy2mac", "phy2mac_lane_t")):
        sigs = [s for s in cfg.signals if s.direction == d and s.sel_src == "sel"]
        L.append(f"    // {d} 方向，走 BBM 的信号打包成一个类型；")
        L.append(f"    // 走 sel_tgt 的信号（ResetN）单独走线，不在此列。")
        L.append("    typedef struct packed {")
        for s in sigs:
            w = "" if s.width == 1 else f"[{s.width-1}:0] "
            L.append(f"        logic {w}{s.name};")
        L.append(f"    }} {tname};")
        L.append("")

    # 安全态常量
    for d, tname, cname in (("mac2phy", "mac2phy_lane_t", "SAFE_M2P"),
                            ("phy2mac", "phy2mac_lane_t", "SAFE_P2M")):
        sigs = [s for s in cfg.signals if s.direction == d and s.sel_src == "sel"]
        L.append(f"    // 无 owner 时（BBM 交接窗口）应呈现的值。")
        L.append(f"    // onehot_mux 用它做极性归一化，使 sel 全 0 时天然落到安全态。")
        L.append(f"    localparam {tname} {cname} = '{{")
        for i, s in enumerate(sigs):
            tail = "," if i != len(sigs) - 1 else ""
            L.append(f"        {s.name}: {s.sv_literal(s.safe_level)}{tail}")
        L.append("    };")
        L.append("")

    # 每个 group 的 sel 类型
    L.append("    // 每个需要 BBM 的 lane group 一个 one-hot 选择向量。")
    L.append("    // 直连的 group 不出现在这里 —— 从类型层面表明它没有可选项。")
    for g in cfg.groups:
        if g.is_direct:
            c = cfg.controllers[g.cands[0]]
            L.append(f"    // G{g.gid} (lane{g.lanes[0]}~{g.lanes[-1]}): "
                     f"直连 {c.name}，无 sel")
        else:
            names = ", ".join(
                f"bit{i}={cfg.controllers[c].name}" for i, c in enumerate(g.cands))
            L.append(f"    // G{g.gid} (lane{g.lanes[0]}~{g.lanes[-1]}): {names}")
    L.append("    typedef struct packed {")
    any_mux = False
    for g in cfg.groups:
        if not g.is_direct:
            L.append(f"        logic [{g.n-1}:0] g{g.gid};")
            any_mux = True
    if not any_mux:
        L.append("        logic dummy;   // 本拓扑全部直连")
    L.append("    } lane_sel_t;")
    L.append("")
    L.append("endpackage")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 译码

def gen_decoder(cfg):
    nm = len(cfg.modes)
    cp = cfg.ctrl_pclk_src()
    cc = cfg.ctrl_pclk_cands()
    muxed_c = [c for c in sorted(cfg.controllers) if len(cc[c]) > 1]

    L = [BANNER,
         "//",
         "// mode 译码：产生各 lane group 的目标 owner，以及各 controller",
         "// 的目标 pclk 来源。纯组合，无状态。",
         "//",
         "// 输出直接进 BBM 的 tgt 端口，由 BBM 完成跨域同步与互锁。",
         "import pipe_pkg::*;",
         "",
         "module pipe_lane_decoder #(",
         f"    parameter int NUM_MODES = {nm},",
         f"    /* verilator lint_off UNUSEDPARAM */",
         f"    parameter int NUM_CTRL  = {cfg.num_ctrl}   // 候选多于一个的 controller 才用到",
         f"    /* verilator lint_on UNUSEDPARAM */",
         ") (",
         "    input  logic [$clog2(NUM_MODES)-1:0] mode,"]
    # 输出端口列表：sel_tgt 必有，pclk_tgt 按需追加
    ports = ["    output lane_sel_t sel_tgt"]
    for c in muxed_c:
        ports.append(f"    output logic [{len(cc[c])-1}:0] "
                     f"pclk_tgt_c{c},   // {cfg.controllers[c].name} 的 pclk 候选选择")
    # 去掉最后一个端口的行尾逗号
    ports[-1] = ports[-1].rstrip(",")
    L.extend(ports)
    L.append(");")
    L.append("")

    mux_groups = [g for g in cfg.groups if not g.is_direct]
    L.append("    always_comb begin")
    L.append("        sel_tgt = '0;")
    for c in muxed_c:
        L.append(f"        pclk_tgt_c{c} = '0;")
    L.append("")
    L.append("        unique case (mode)")
    for m in cfg.modes:
        L.append(f"            {m}: begin")
        for g in mux_groups:
            b = g.branch_of(g.owners[m])
            L.append(f"                sel_tgt.g{g.gid} = {g.n}'b{1 << b:0{g.n}b};"
                     f"  // {cfg.controllers[g.owners[m]].name}")
        for c in muxed_c:
            v = cp[c][m]
            if v is None:
                L.append(f"                // {cfg.controllers[c].name} 本 mode 未分到 lane，")
                L.append(f"                // pclk_tgt 保持 0，由下游 hold 逻辑维持上次选择")
            else:
                b = cc[c].index(v)
                L.append(f"                pclk_tgt_c{c} = "
                         f"{len(cc[c])}'b{1 << b:0{len(cc[c])}b};  // phy_pclk[{v}]")
        L.append("            end")
    L.append("            default: begin")
    L.append("                sel_tgt = '0;")
    for c in muxed_c:
        L.append(f"                pclk_tgt_c{c} = '0;")
    L.append("            end")
    L.append("        endcase")
    L.append("    end")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 时钟子模块

def gen_clk_top(cfg):
    """ctrl_pclk 生成 + group BBM + 反馈时钟。"""
    nm = len(cfg.modes)
    LC, NC = cfg.lane_count, cfg.num_ctrl
    cp, cc = cfg.ctrl_pclk_src(), cfg.ctrl_pclk_cands()
    muxed_c = [c for c in sorted(cfg.controllers) if len(cc[c]) > 1]

    L = [BANNER, "//",
         "// PIPE lane mapper 时钟子模块。",
         "// 包含：controller pclk 生成、group BBM、反馈时钟 mux。",
         "// 数据 mux 在 pipe_lane_data_m2p / pipe_lane_data_p2m 中。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_clk_top #(",
         f"    parameter int NUM_MODES  = {nm},",
         f"    parameter int LANE_COUNT = {LC},",
         f"    parameter int NUM_CTRL   = {NC}",
         ") (",
         "    /* verilator lint_off UNUSEDSIGNAL */",
         "    input  logic [LANE_COUNT-1:0] phy_pclk_out,",
         "    /* verilator lint_on UNUSEDSIGNAL */",
         "    input  logic                  test_en,",
         "    input  logic [$clog2(NUM_MODES)-1:0] mode,",
         ""]

    # controller 侧 mac2phy 端口（只取 phy_rst_n）
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    // {c.name} x{c.max_width}")
        L.append(f"    input  mac2phy_lane_t [{c.max_width-1}:0] {c.lname}_mac2phy,")
    L[-1] = L[-1].rstrip(",")

    L.append("");  L.append("    output logic [NUM_CTRL-1:0]   ctrl_pclk,")
    L.append("    output logic [LANE_COUNT-1:0] phy_pclk_in,")
    L.append("    output lane_sel_t              sel,")
    L.append("    output lane_sel_t              sel_tgt")
    L.append(");")
    L.append("")

    # 内部信号
    for c in muxed_c:
        L.append(f"    logic [{len(cc[c])-1}:0] pclk_tgt_c{c};")
    L.append("")

    # 译码例化
    L.append("    pipe_lane_decoder #(")
    L.append("        .NUM_MODES (NUM_MODES),")
    L.append("        .NUM_CTRL  (NUM_CTRL)")
    L.append("    ) u_decoder (")
    L.append("        .mode     (mode),")
    L.append("        .sel_tgt  (sel_tgt)" + ("," if muxed_c else ""))
    for i, c in enumerate(muxed_c):
        tail = "," if i != len(muxed_c) - 1 else ""
        L.append(f"        .pclk_tgt_c{c} (pclk_tgt_c{c}){tail}")
    L.append("    );")
    L.append("")

    # ctrl_pclk
    L.append("    //------------------------------------------------------------")
    L.append("    // controller pclk：固定取组内最低编号 lane 的 phy_pclk。")
    L.append("    // 候选多于一个的才需要无毛刺切换。")
    L.append("    //------------------------------------------------------------")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        cand = cc[cid]
        if len(cand) == 1:
            L.append(f"    // {c.name}: 所有 mode 都用 phy_pclk[{cand[0]}]，直连")
            L.append(f"    assign ctrl_pclk[{cid}] = phy_pclk_out[{cand[0]}];")
        else:
            n = len(cand)
            L.append(f"    // {c.name}: {n} 选 1，候选 "
                     f"{', '.join(f'phy_pclk[{v}]' for v in cand)}")
            L.append(f"    logic [{n-1}:0] pclk_tgt_hold_c{cid};")
            L.append(f"    logic [{n-1}:0] pen_c{cid};")
            L.append(f"    logic [{n-1}:0] pgated_c{cid};")
            L.append(f"    always_ff @(posedge phy_pclk_out[{cand[0]}] "
                     f"or negedge {c.lname}_mac2phy[0].phy_rst_n)")
            L.append(f"        if (!{c.lname}_mac2phy[0].phy_rst_n) pclk_tgt_hold_c{cid} <= "
                     f"{n}'b{1:0{n}b};")
            L.append(f"        else if (|pclk_tgt_c{cid}) pclk_tgt_hold_c{cid} <= "
                     f"pclk_tgt_c{cid};")
            L.append(f"    bbm_sel_onehot #(.N({n})) u_pclk_bbm_c{cid} (")
            L.append(f"        .branch_clk   ({{"
                     + ", ".join(f"phy_pclk_out[{v}]" for v in reversed(cand)) + "}),")
            L.append(f"        .branch_rst_n ({{{n}{{{c.lname}_mac2phy[0].phy_rst_n}}}}),")
            L.append(f"        .tgt          (pclk_tgt_hold_c{cid}),")
            L.append(f"        .en           (pen_c{cid})")
            L.append(f"    );")
            for i, v in enumerate(cand):
                L.append(f"    clk_gate u_pclk_gate_c{cid}_b{i} ("
                         f".clk_in(phy_pclk_out[{v}]), .en(pen_c{cid}[{i}]), "
                         f".test_en(test_en), .clk_out(pgated_c{cid}[{i}]));")
            L.append(f"    assign ctrl_pclk[{cid}] = |pgated_c{cid};")
        L.append("")

    # group BBM
    L.append("    //------------------------------------------------------------")
    L.append("    // 每个非直连 group 一个 BBM。")
    L.append("    //------------------------------------------------------------")
    for g in cfg.groups:
        if g.is_direct:
            continue
        names = ", ".join(cfg.controllers[c].name for c in g.cands)
        L.append(f"    // G{g.gid} lane{g.lanes[0]}~{g.lanes[-1]}: {names}")
        L.append(f"    bbm_sel_onehot #(.N({g.n})) u_bbm_g{g.gid} (")
        L.append(f"        .branch_clk   ({{"
                 + ", ".join(f"ctrl_pclk[{c}]" for c in reversed(g.cands)) + "}),")
        L.append(f"        .branch_rst_n ({{"
                 + ", ".join(f"{cfg.controllers[c].lname}_mac2phy[0].phy_rst_n" for c in reversed(g.cands)) + "}),")
        L.append(f"        .tgt          (sel_tgt.g{g.gid}),")
        L.append(f"        .en           (sel.g{g.gid})")
        L.append(f"    );")
        L.append("")

    # 反馈时钟
    L.append("    //------------------------------------------------------------")
    L.append("    // 反馈时钟：每条 lane 的 pclk_in 接它当前 owner 的 ctrl_pclk。")
    L.append("    // 与数据共用同一组 en，保证数据与时钟同步切换。")
    L.append("    //------------------------------------------------------------")
    for g in cfg.groups:
        if g.is_direct:
            c = g.cands[0]
            for l in g.lanes:
                L.append(f"    assign phy_pclk_in[{l}] = ctrl_pclk[{c}];"
                         f"  // G{g.gid} 直连 {cfg.controllers[c].name}")
        else:
            names = ", ".join(cfg.controllers[c].name for c in g.cands)
            L.append(f"    // G{g.gid} lane{g.lanes[0]}~{g.lanes[-1]}: {names}")
            L.append(f"    logic [{g.n-1}:0] pin_gated_g{g.gid};")
            for i, c in enumerate(g.cands):
                L.append(f"    clk_gate u_pin_gate_g{g.gid}_b{i} ("
                         f".clk_in(ctrl_pclk[{c}]), .en(sel.g{g.gid}[{i}]), "
                         f".test_en(test_en), .clk_out(pin_gated_g{g.gid}[{i}]));")
            for idx, l in enumerate(g.lanes):
                if idx == 0:
                    L.append(f"    assign phy_pclk_in[{l}] = |pin_gated_g{g.gid};")
                else:
                    L.append(f"    assign phy_pclk_in[{l}] = phy_pclk_in[{g.lanes[0]}];")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- MAC->PHY 数据

def gen_data_m2p(cfg):
    """mac2phy 方向数据 mux。"""
    LC = cfg.lane_count
    L = [BANNER, "//",
         "// PIPE lane mapper MAC->PHY 数据 mux。",
         "// onehot_mux 内部做极性归一化，sel 全 0 时输出 SAFE_M2P。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_data_m2p #(",
         f"    parameter int LANE_COUNT = {LC}",
         ") (",
         "    input  lane_sel_t              sel,",
         "    output mac2phy_lane_t [LANE_COUNT-1:0] phy_mac2phy,"]
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    input  mac2phy_lane_t [{c.max_width-1}:0] {c.lname}_mac2phy,")
    L[-1] = L[-1].rstrip(",")
    L.append(");")
    L.append("")

    for g in cfg.groups:
        for l in g.lanes:
            if g.is_direct:
                c = g.cands[0]
                cl = cfg.mapping[cfg.modes[0]][l][1]
                L.append(f"    assign phy_mac2phy[{l}] = "
                         f"{cfg.controllers[c].lname}_mac2phy[{cl}];  // 直连")
            else:
                srcs = []
                for c in g.cands:
                    m = next(mm for mm in cfg.modes if g.owners[mm] == c)
                    cl = cfg.mapping[m][l][1]
                    srcs.append(f"{cfg.controllers[c].lname}_mac2phy[{cl}]")
                L.append(f"    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), "
                         f".N({g.n}), .SAFE(SAFE_M2P)) u_m2p_l{l} (")
                L.append(f"        .sel  (sel.g{g.gid}),")
                L.append(f"        .din  ({{" + ", ".join(reversed(srcs)) + "}),")
                L.append(f"        .dout (phy_mac2phy[{l}])")
                L.append(f"    );")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- PHY->MAC 数据

def gen_data_p2m(cfg):
    """phy2mac 方向数据 mux（按 controller 端口汇聚）。"""
    LC = cfg.lane_count
    L = [BANNER, "//",
         "// PIPE lane mapper PHY->MAC 数据 mux（按 controller 端口汇聚）。",
         "// sel 的互斥性由 BBM 保证。未被驱动的端口 tie 安全态。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_data_p2m #(",
         f"    parameter int LANE_COUNT = {LC}",
         ") (",
         "    input  lane_sel_t              sel,",
         "    input  phy2mac_lane_t [LANE_COUNT-1:0] phy_phy2mac,"]
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    output phy2mac_lane_t [{c.max_width-1}:0] {c.lname}_phy2mac,")
    L[-1] = L[-1].rstrip(",")
    L.append(");")
    L.append("")

    port_src = {}
    for m in cfg.modes:
        for l in range(LC):
            cid, cl = cfg.mapping[m][l]
            g = cfg.group_of_lane(l)
            b = 0 if g.is_direct else g.branch_of(cid)
            port_src.setdefault((cid, cl), set()).add((l, g.gid, b))
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    // {c.name} x{c.max_width}")
        for cl in range(c.max_width):
            srcs = sorted(port_src.get((cid, cl), set()))
            if not srcs:
                L.append(f"    assign {c.lname}_phy2mac[{cl}] = SAFE_P2M;"
                         f"  // 所有 mode 下都未被驱动")
                continue
            if len(srcs) == 1 and cfg.groups[srcs[0][1]].is_direct:
                l = srcs[0][0]
                L.append(f"    assign {c.lname}_phy2mac[{cl}] = phy_phy2mac[{l}];"
                         f"  // 直连 lane{l}")
                continue
            gid = srcs[0][1]
            g = cfg.groups[gid]
            din = []
            for i in range(g.n):
                hit = [s for s in srcs if s[2] == i]
                if hit:
                    din.append(f"phy_phy2mac[{hit[0][0]}]")
                else:
                    din.append("SAFE_P2M")
            L.append(f"    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), "
                     f".N({g.n}), .SAFE(SAFE_P2M)) u_p2m_{c.lname}_{cl} (")
            L.append(f"        .sel  (sel.g{gid}),")
            L.append(f"        .din  ({{" + ", ".join(reversed(din)) + "}),")
            L.append(f"        .dout ({c.lname}_phy2mac[{cl}])")
            L.append(f"    );")
        L.append("")

    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 顶层

def gen_top(cfg):
    nm = len(cfg.modes)
    LC, NC = cfg.lane_count, cfg.num_ctrl
    tgt_sigs = [s for s in cfg.signals if s.sel_src == "sel_tgt"]

    L = [BANNER, "//"]
    L.append("// PIPE lane mapper 顶层。")
    L.append("//")
    L.append("// 纯例化层：时钟/BBM 在 pipe_lane_clk_top，")
    L.append("// MAC->PHY 数据 mux 在 pipe_lane_data_m2p，")
    L.append("// PHY->MAC 数据 mux 在 pipe_lane_data_p2m。")
    L.append("//")
    L.append("// lane 分组：归属序列相同的 lane 自动成组，共享一个 BBM。")
    L.append("//")
    for g in cfg.groups:
        rng = f"lane{g.lanes[0]}~{g.lanes[-1]}" if len(g.lanes) > 1 else f"lane{g.lanes[0]}"
        owners = " / ".join(cfg.controllers[g.owners[m]].name for m in cfg.modes)
        kind = "直连" if g.is_direct else f"{g.n} 选 1 BBM"
        L.append(f"//   G{g.gid} {rng:<14} {owners:<24} {kind}")
    L.append("import pipe_pkg::*;")
    L.append("")
    L.append("module pipe_lane_mapper_top #(")
    L.append(f"    parameter int NUM_MODES  = {nm},")
    L.append(f"    parameter int LANE_COUNT = {LC},")
    L.append(f"    parameter int NUM_CTRL   = {NC}")
    L.append(") (")
    L.append("    /* verilator lint_off UNUSEDSIGNAL */")
    L.append("    input  logic [LANE_COUNT-1:0] phy_pclk_out,")
    L.append("    /* verilator lint_on UNUSEDSIGNAL */")
    L.append("    input  logic                  test_en,")
    L.append("    input  logic [$clog2(NUM_MODES)-1:0] mode,")
    L.append("")
    L.append("    output logic [NUM_CTRL-1:0]   ctrl_pclk,")
    L.append("    output logic [LANE_COUNT-1:0] phy_pclk_in,")
    L.append("")
    L.append("    // PHY 侧 PIPE 数据")
    L.append("    output mac2phy_lane_t [LANE_COUNT-1:0] phy_mac2phy,")
    L.append("    input  phy2mac_lane_t [LANE_COUNT-1:0] phy_phy2mac,")
    for s in tgt_sigs:
        io = "output" if s.is_m2p else "input "
        w = "" if s.width == 1 else f"[{s.width-1}:0] "
        L.append(f"    {io} logic {w}phy_{s.name} [0:LANE_COUNT-1],"
                 f"  // 走 sel_tgt，不经 BBM")
    L.append("")
    L.append("    // Controller 侧，各自真实宽度")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    // {c.name} x{c.max_width}")
        L.append(f"    input  mac2phy_lane_t [{c.max_width-1}:0] {c.lname}_mac2phy,")
        L.append(f"    output phy2mac_lane_t [{c.max_width-1}:0] {c.lname}_phy2mac,")
        for s in tgt_sigs:
            io = "input " if s.is_m2p else "output"
            w = "" if s.width == 1 else f"[{s.width-1}:0] "
            L.append(f"    {io} logic {w}{c.lname}_{s.name} [0:{c.max_width-1}],")
    L[-1] = L[-1].rstrip(",")
    L.append(");")
    L.append("")

    # ---- 内部连线
    L.append("    lane_sel_t sel;")
    L.append("    lane_sel_t sel_tgt;")
    L.append("")

    # ---- 时钟子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // 时钟子模块：ctrl_pclk 生成 + group BBM + 反馈时钟 mux")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_clk_top #(")
    L.append("        .NUM_MODES  (NUM_MODES),")
    L.append("        .LANE_COUNT (LANE_COUNT),")
    L.append("        .NUM_CTRL   (NUM_CTRL)")
    L.append("    ) u_clk_top (")
    L.append("        .phy_pclk_out (phy_pclk_out),")
    L.append("        .test_en      (test_en),")
    L.append("        .mode         (mode),")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"        .{c.lname}_mac2phy ({c.lname}_mac2phy),")
    L.append("        .ctrl_pclk    (ctrl_pclk),")
    L.append("        .phy_pclk_in  (phy_pclk_in),")
    L.append("        .sel          (sel),")
    L.append("        .sel_tgt      (sel_tgt)")
    L.append("    );")
    L.append("")

    # ---- MAC->PHY 数据子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // MAC->PHY 数据 mux")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_data_m2p #(")
    L.append("        .LANE_COUNT (LANE_COUNT)")
    L.append("    ) u_data_m2p (")
    L.append("        .sel          (sel),")
    L.append("        .phy_mac2phy  (phy_mac2phy),")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"        .{c.lname}_mac2phy ({c.lname}_mac2phy),")
    L[-1] = L[-1].rstrip(",")
    L.append("    );")
    L.append("")

    # ---- PHY->MAC 数据子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // PHY->MAC 数据 mux")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_data_p2m #(")
    L.append("        .LANE_COUNT (LANE_COUNT)")
    L.append("    ) u_data_p2m (")
    L.append("        .sel          (sel),")
    L.append("        .phy_phy2mac  (phy_phy2mac),")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"        .{c.lname}_phy2mac ({c.lname}_phy2mac),")
    L[-1] = L[-1].rstrip(",")
    L.append("    );")
    L.append("")

    # ---- sel_tgt 直通信号
    if tgt_sigs:
        L.append("    //------------------------------------------------------------")
        L.append("    // 走 sel_tgt 的信号：不经 BBM，直接按目标 owner 选。")
        L.append("    //------------------------------------------------------------")
        for s in tgt_sigs:
            for g in cfg.groups:
                for l in g.lanes:
                    if g.is_direct:
                        c = g.cands[0]
                        cl = cfg.mapping[cfg.modes[0]][l][1]
                        if s.is_m2p:
                            L.append(f"    assign phy_{s.name}[{l}] = "
                                     f"{cfg.controllers[c].lname}_{s.name}[{cl}];")
                    else:
                        if s.is_m2p:
                            terms = []
                            for i, c in enumerate(g.cands):
                                m = next(mm for mm in cfg.modes if g.owners[mm] == c)
                                cl = cfg.mapping[m][l][1]
                                terms.append(
                                    f"({cfg.controllers[c].lname}_{s.name}[{cl}] "
                                    f"& {{{s.width}{{sel_tgt.g{g.gid}[{i}]}}}})")
                            safe = s.sv_literal(s.safe_level)
                            terms.append(
                                f"({safe} & {{{s.width}{{~|sel_tgt.g{g.gid}}}}})")
                            L.append(f"    assign phy_{s.name}[{l}] =")
                            for k, t in enumerate(terms):
                                sep = ";" if k == len(terms) - 1 else ""
                                pre = "          " if k == 0 else "        | "
                                L.append(f"    {pre}{t}{sep}")
        L.append("")

    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- filelist

def gen_filelist(cfg, outdir, gendir):
    common = ["sync2.sv", "bbm_sel_onehot.sv", "clk_gate.sv", "onehot_mux.sv"]
    gen = [
        "pipe_pkg.sv",
        "pipe_lane_decoder.sv",
        "pipe_lane_clk_top.sv",
        "pipe_lane_data_m2p.sv",
        "pipe_lane_data_p2m.sv",
        "pipe_lane_mapper_top.sv",
    ]
    L = ["// Auto-generated by tools/plm_gen.py -- DO NOT EDIT",
         "// RTL filelist。package 必须排在使用它的模块之前。",
         "",
         "+incdir+${PLM_ROOT}/rtl/common",
         "+incdir+${PLM_ROOT}/rtl/gen",
         ""]
    for f in common:
        L.append(f"${{PLM_ROOT}}/rtl/common/{f}")
    L.append("")
    for f in gen:
        L.append(f"${{PLM_ROOT}}/{gendir}/{f}")
    return "\n".join(L) + "\n"


def gen_sim_filelist(cfg, gendir):
    L = ["// Auto-generated by tools/plm_gen.py -- DO NOT EDIT",
         "// 仿真 filelist：RTL + testbench。",
         "",
         "-f ${PLM_ROOT}/filelist/rtl.f",
         "",
         "${PLM_ROOT}/verify/tb_pipe_lane_mapper.sv"]
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description="生成 PIPE lane mapper RTL")
    ap.add_argument("--config", default="config")
    ap.add_argument("--outdir", default="rtl/gen")
    ap.add_argument("--filelist", default="filelist")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()

    cfg = load(a.config)
    out = Path(a.outdir)
    out.mkdir(parents=True, exist_ok=True)
    fl = Path(a.filelist)
    fl.mkdir(parents=True, exist_ok=True)

    files = {
        out / "pipe_pkg.sv": gen_pkg(cfg),
        out / "pipe_lane_decoder.sv": gen_decoder(cfg),
        out / "pipe_lane_clk_top.sv": gen_clk_top(cfg),
        out / "pipe_lane_data_m2p.sv": gen_data_m2p(cfg),
        out / "pipe_lane_data_p2m.sv": gen_data_p2m(cfg),
        out / "pipe_lane_mapper_top.sv": gen_top(cfg),
        fl / "rtl.f": gen_filelist(cfg, out, a.outdir),
        fl / "sim.f": gen_sim_filelist(cfg, a.outdir),
    }
    for p, c in files.items():
        p.write_text(c)
        print(f"  生成 {p}")

    if not a.quiet:
        print()
        print(cfg.report())


if __name__ == "__main__":
    main()
