#!/usr/bin/env python3
"""
PIPE Lane Mapper RTL 生成器。

只生成配置相关的部分：类型定义、mode 译码、以及 common 模块的例化与接线。
BBM、同步器、时钟门控、one-hot mux 都是 script/common 下的手写模块，不随配置变。
"""

import argparse
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PLM_ROOT = SCRIPT_DIR.parent
BUILTIN_CFG = SCRIPT_DIR / "config"          # 内置默认 CSV
COMMON_DIR = SCRIPT_DIR / "common"          # 手写公共模块（不随配置变，随 script 交付）
CSV_NAMES = ("controllers.csv", "lane_mapping.csv", "pipe_signals.csv")

sys.path.insert(0, str(SCRIPT_DIR))
from plm_config import load          # noqa: E402

BANNER = "// Auto-generated by script/plm_gen.py -- DO NOT EDIT"


def has_csvs(d):
    d = Path(d)
    return d.is_dir() and all((d / n).is_file() for n in CSV_NAMES)


def resolve_set(arg):
    """把 --config 参数解析成 (csv_dir, out_rtl)。

    约定：一个配置集是一个目录，生成物固定输出到 <集>/rtl/ 下；
    CSV 的查找顺序是 <集>/config/ -> <集>/ 本身 -> 内置 script/config/。
    所以：
      --config config-1          -> 读 config-1/config/（或 config-1/），
                                     生成到 config-1/rtl/
      --config config-1/config   -> 同上（传 config 子目录也归到上一级集）
    默认（不带 --config）用 <plm根>/config 这个集，其 CSV 取内置的
    script/config/，生成到 <plm根>/config/rtl/。
    """
    if arg is None:
        set_dir = PLM_ROOT / "config"
    else:
        set_dir = Path(arg).resolve()
    if has_csvs(set_dir / "config"):
        return set_dir / "config", set_dir / "rtl"
    if has_csvs(set_dir):
        # 传进来的是某个集的 config 子目录（如 config-1/config）：
        # 归属上一级集合，生成物仍落 config-1/rtl
        if set_dir.name == "config" and set_dir.parent != SCRIPT_DIR:
            return set_dir, set_dir.parent / "rtl"
        return set_dir, set_dir / "rtl"
    if has_csvs(BUILTIN_CFG):
        return BUILTIN_CFG, set_dir / "rtl"
    raise SystemExit(
        f"{set_dir} 下找不到 CSV（{', '.join(CSV_NAMES)}），"
        f"内置默认配置在 {BUILTIN_CFG}")


# ---------------------------------------------------------------- 类型包

def gen_pkg(cfg):
    L = [BANNER, "package pipe_pkg;", ""]

    for d, tname in (("mac2phy", "mac2phy_lane_t"), ("phy2mac", "phy2mac_lane_t")):
        sigs = [s for s in cfg.signals if s.direction == d]
        L.append(f"    // {d} 方向，走 BBM 的信号打包成一个类型；")
        L.append("    typedef struct packed {")
        for s in sigs:
            w = "" if s.width == 1 else f"[{s.width-1}:0] "
            L.append(f"        logic {w}{s.name};")
        L.append(f"    }} {tname};")
        L.append("")

    # 安全态常量
    for d, tname, cname in (("mac2phy", "mac2phy_lane_t", "SAFE_M2P"),
                            ("phy2mac", "phy2mac_lane_t", "SAFE_P2M")):
        sigs = [s for s in cfg.signals if s.direction == d]
        L.append(f"    // 无 owner 时（BBM 交接窗口）应呈现的值。")
        L.append(f"    // onehot_mux 用它做极性归一化，使 sel 全 0 时天然落到安全态。")
        L.append(f"    localparam {tname} {cname} = '{{")
        for i, s in enumerate(sigs):
            tail = "," if i != len(sigs) - 1 else ""
            L.append(f"        {s.name}: {s.sv_literal(s.safe_state)}{tail}")
        L.append("    };")
        L.append("")

    # 每个 group 的 sel 类型
    L.append("    // 每个需要 BBM 的 lane group 一个 one-hot 选择向量。")
    L.append("    // 直连的 group 不出现在这里 —— 从类型层面表明它没有可选项。")
    for g in cfg.groups:
        if g.is_direct:
            c = cfg.controllers[g.cands[0]]
            L.append(f"    // G{g.gid} (lane{g.lanes[0]}~{g.lanes[-1]}): "
                     f"直连 {c.name}，无 sel")
        else:
            names = ", ".join(
                f"bit{i}={cfg.controllers[c].name}" for i, c in enumerate(g.cands))
            L.append(f"    // G{g.gid} (lane{g.lanes[0]}~{g.lanes[-1]}): {names}")
    L.append("    typedef struct packed {")
    any_mux = False
    for g in cfg.groups:
        if not g.is_direct:
            L.append(f"        logic [{g.n-1}:0] g{g.gid};")
            any_mux = True
    if not any_mux:
        L.append("        logic dummy;   // 本拓扑全部直连")
    L.append("    } lane_sel_t;")
    L.append("")
    L.append("endpackage")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 译码

def gen_decoder(cfg):
    nm = len(cfg.modes)
    cp = cfg.ctrl_pclk_src()
    cc = cfg.ctrl_pclk_cands()
    muxed_c = [c for c in sorted(cfg.controllers) if len(cc[c]) > 1]

    L = [BANNER,
         "//",
         "// mode 译码：产生各 lane group 的目标 owner，以及各 controller",
         "// 的目标 pclk 来源。纯组合，无状态。",
         "//",
         "// 输出直接进 BBM 的 tgt 端口，由 BBM 完成跨域同步与互锁。",
         "import pipe_pkg::*;",
         "",
         "module pipe_lane_decoder #(",
         f"    parameter int NUM_MODES = {nm},",
         f"    /* verilator lint_off UNUSEDPARAM */",
         f"    parameter int NUM_CTRL  = {cfg.num_ctrl}   // 候选多于一个的 controller 才用到",
         f"    /* verilator lint_on UNUSEDPARAM */",
         ") (",
         "    input  logic [$clog2(NUM_MODES)-1:0] mode,"]
    # 输出端口列表：sel_tgt 必有，pclk_tgt 按需追加。逗号必须插在注释
    # 之前——直接 append(",") 到整行末尾会把逗号加进 "// ..." 注释里，
    # 代码本身仍然漏逗号，所以这里把「代码」和「注释」分开拼，逗号加在
    # 代码尾部，注释单独接在后面。
    ports = [("    output lane_sel_t sel_tgt", "")]
    for c in muxed_c:
        ports.append((f"    output logic [{len(cc[c])-1}:0] pclk_tgt_c{c}",
                      f"   // {cfg.controllers[c].name} 的 pclk 候选选择"))
    for i, (code, comment) in enumerate(ports):
        tail = "," if i != len(ports) - 1 else ""
        L.append(code + tail + comment)
    L.append(");")
    L.append("")

    mux_groups = [g for g in cfg.groups if not g.is_direct]
    L.append("    always_comb begin")
    L.append("        sel_tgt = '0;")
    for c in muxed_c:
        L.append(f"        pclk_tgt_c{c} = '0;")
    L.append("")
    L.append("        unique case (mode)")
    for m in cfg.modes:
        L.append(f"            {m}: begin")
        for g in mux_groups:
            b = g.branch_of(g.owners[m])
            L.append(f"                sel_tgt.g{g.gid} = {g.n}'b{1 << b:0{g.n}b};"
                     f"  // {cfg.controllers[g.owners[m]].name}")
        for c in muxed_c:
            v = cp[c][m]
            if v is None:
                L.append(f"                // {cfg.controllers[c].name} 本 mode 未分到 lane，")
                L.append(f"                // pclk_tgt 保持 0，由下游 hold 逻辑维持上次选择")
            else:
                b = cc[c].index(v)
                L.append(f"                pclk_tgt_c{c} = "
                         f"{len(cc[c])}'b{1 << b:0{len(cc[c])}b};  // phy_pclk[{v}]")
        L.append("            end")
    L.append("            default: begin")
    L.append("                sel_tgt = '0;")
    for c in muxed_c:
        L.append(f"                pclk_tgt_c{c} = '0;")
    L.append("            end")
    L.append("        endcase")
    L.append("    end")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 选择生成子模块

def gen_sel_gen(cfg, sel_mode="sync"):
    """选择生成子模块：mode 译码 + group sel_sync，产生 sel_tgt 与 dec_tgt。

    以前译码器 + group sel_sync 是塞在时钟子模块里的，现在拆成独立的
    pipe_lane_sel_gen，职责更清楚：本模块只回答“当前各 group 该听谁的”，
    不碰任何时钟生成逻辑。

    对外有两份目标信号：
      sel_tgt -- 经 sel_sync 同步后的最终生效选择，break-before-make，
                 给 clk_mux 的反馈时钟 mux、data_m2p/data_p2m 用。
      dec_tgt -- 译码器的原始（未同步）目标，纯组合、随 mode 直接变化，
                 给 rst_mux 用：让新 owner 的复位控制提前跟着 mode 走，
                 不必等 sel_sync 完成跨时钟域同步和 BBM 的 break 窗口。

    controller 侧的 pclk 候选（pclk_tgt_cX）也是内部译码器产生的，但那份
    信号是给 pipe_lane_clk_mux 用来做 controller pclk 无毛刺切换的，本
    模块自己不消费，只是透传出去。

    group 的 owner 选择走 sel_sync 模块（script/common/sel_sync.sv），
    用它的 SYNC 参数在两种实现之间切换：
      sel_mode="sync" (默认) -- SYNC=1'b1，break-before-make + 两级同步器，
                跨时钟域安全。
      sel_mode="comb"        -- SYNC=1'b0，en 直接等于 tgt，纯组合直通。
                只在所有候选 controller 确实共用同一个时钟域、mode 本身
                在该域内无毛刺时才安全；否则可能瞬间多个分支同时为 1，
                onehot_mux 会把两路数据相或。

    本模块需要 ctrl_pclk 作为输入（group sel_sync 的 branch_clk），而
    ctrl_pclk 是 pipe_lane_clk_mux 的输出 —— 两个子模块在顶层是环形连线，
    但没有组合环：ctrl_pclk 只依赖译码器的 pclk_tgt_cX（本模块透传），
    与本模块产生的 sel_tgt 无关；sel_tgt 依赖 ctrl_pclk 则全部经过
    sel_sync 内部的触发器，不存在组合反馈。
    """
    nm = len(cfg.modes)
    NC = cfg.num_ctrl
    cc = cfg.ctrl_pclk_cands()
    muxed_c = [c for c in sorted(cfg.controllers) if len(cc[c]) > 1]
    sync_lit = "1'b1" if sel_mode == "sync" else "1'b0"

    L = [BANNER, "//",
         "// PIPE lane mapper 选择生成子模块。",
         "// 译码 mode 得到各 group 的原始目标 dec_tgt（组合，给 rst_mux），",
         "// 再用 sel_sync 做 break-before-make + 跨时钟域同步，产生最终",
         "// 生效的 sel_tgt（给 clk_mux 的反馈时钟 mux、data mux）。",
         "// pclk_tgt_cX 由内部译码器产生，透传给 pipe_lane_clk_mux",
         "// 用于 controller pclk 候选的无毛刺切换。",
         f"// group 的 sel_sync 模式: {sel_mode}"
         + (" (SYNC=1, 跨时钟域安全)" if sel_mode == "sync"
            else " (SYNC=0, 组合直通，要求候选 controller 共用同一时钟域)"),
         "import pipe_pkg::*;",
         "",
         "module pipe_lane_sel_gen #(",
         f"    parameter int NUM_MODES = {nm},",
         f"    parameter int NUM_CTRL  = {NC}",
         ") (",
         "    input  logic [$clog2(NUM_MODES)-1:0] mode,",
         "    input  logic [NUM_CTRL-1:0]   ctrl_pclk,",
         "    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,",
         ""]
    # 同 gen_decoder：代码与注释分开拼，逗号加在代码尾部、注释之前。
    ports = [("    output lane_sel_t sel_tgt",
              "   // 经 sel_sync 同步后的最终生效选择，给 clk_mux/data mux 用"),
             ("    output lane_sel_t dec_tgt",
              "   // 译码器的原始（未同步）目标，给 rst_mux 用")]
    for c in muxed_c:
        ports.append((f"    output logic [{len(cc[c])-1}:0] pclk_tgt_c{c}",
                      f"   // {cfg.controllers[c].name} 的 pclk 候选，透传给 clk_mux"))
    for i, (code, comment) in enumerate(ports):
        tail = "," if i != len(ports) - 1 else ""
        L.append(code + tail + comment)
    L.append(");")
    L.append("")

    # 译码例化
    L.append("    pipe_lane_decoder #(")
    L.append("        .NUM_MODES (NUM_MODES),")
    L.append("        .NUM_CTRL  (NUM_CTRL)")
    L.append("    ) u_decoder (")
    L.append("        .mode     (mode),")
    L.append("        .sel_tgt  (dec_tgt)" + ("," if muxed_c else ""))
    for i, c in enumerate(muxed_c):
        tail = "," if i != len(muxed_c) - 1 else ""
        L.append(f"        .pclk_tgt_c{c} (pclk_tgt_c{c}){tail}")
    L.append("    );")
    L.append("")

    L.append("    //------------------------------------------------------------")
    L.append(f"    // 每个非直连 group 一个 sel_sync（SYNC={sync_lit}）。")
    L.append("    //------------------------------------------------------------")
    for g in cfg.groups:
        if g.is_direct:
            continue
        names = ", ".join(cfg.controllers[c].name for c in g.cands)
        L.append(f"    // G{g.gid} lane{g.lanes[0]}~{g.lanes[-1]}: {names}")
        L.append(f"    sel_sync #(.N({g.n}), .SYNC({sync_lit})) u_sel_sync_g{g.gid} (")
        L.append(f"        .branch_clk   ({{"
                 + ", ".join(f"ctrl_pclk[{c}]" for c in reversed(g.cands)) + "}),")
        L.append(f"        .branch_rst_n ({{"
                 + ", ".join(f"ctrl_rst_n[{c}]" for c in reversed(g.cands)) + "}),")
        L.append(f"        .tgt          (dec_tgt.g{g.gid}),")
        L.append(f"        .en           (sel_tgt.g{g.gid})")
        L.append(f"    );")
        L.append("")

    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 时钟 mux 子模块

def gen_clk_mux(cfg):
    """controller pclk 生成 + 反馈时钟 mux。

    group 最终生效的 owner 选择（sel_tgt）现在由 pipe_lane_sel_gen 产生，
    本模块只负责两件事：
      1. controller pclk 候选的无毛刺切换：pclk_tgt_cX 由 sel_gen 内部的
         译码器产生并透传进来，但切换动作仍放在这里完成，因为无毛刺
         切换需要本模块手上的 phy_pclk_out 做跨时钟域同步。
      2. 反馈时钟：每条 lane 的 phy_pclk_in 按 sel_tgt（sel_gen 的输出，
         这里作为输入传入）选到当前 owner 的 ctrl_pclk。

    controller pclk 候选切换始终强制 SYNC=1'b1 —— 那是给时钟本身做无
    毛刺切换，与 group 的 sel_sync 模式无关。
    """
    LC, NC = cfg.lane_count, cfg.num_ctrl
    cc = cfg.ctrl_pclk_cands()
    muxed_c = [c for c in sorted(cfg.controllers) if len(cc[c]) > 1]

    L = [BANNER, "//",
         "// PIPE lane mapper 时钟 mux 子模块。",
         "// 包含：controller pclk 生成、反馈时钟 mux。",
         "// group 的最终 sel_tgt 由 pipe_lane_sel_gen 产生，作为输入传入。",
         "// 反馈复位 mux 在 pipe_lane_rst_mux，数据 mux 在",
         "// pipe_lane_data_m2p / pipe_lane_data_p2m 中。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_clk_mux #(",
         f"    parameter int LANE_COUNT = {LC},",
         f"    parameter int NUM_CTRL   = {NC}",
         ") (",
         "    /* verilator lint_off UNUSEDSIGNAL */",
         "    input  logic [LANE_COUNT-1:0] phy_pclk_out,",
         "    /* verilator lint_on UNUSEDSIGNAL */",
         "    input  logic                  test_en,",
         "    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,",
         ""]
    for c in muxed_c:
        L.append(f"    input  logic [{len(cc[c])-1}:0] pclk_tgt_c{c},"
                 f"   // {cfg.controllers[c].name} 的 pclk 候选目标，来自 sel_gen")
    L.append("    input  lane_sel_t              sel_tgt,   // 各 group 当前实际生效的 owner 选择")
    L.append("")
    L.append("    output logic [NUM_CTRL-1:0]   ctrl_pclk,")
    L.append("    output logic [LANE_COUNT-1:0] phy_pclk_in")
    L.append(");")
    L.append("")

    # ctrl_pclk
    L.append("    //------------------------------------------------------------")
    L.append("    // controller pclk：固定取组内最低编号 lane 的 phy_pclk。")
    L.append("    // 候选多于一个的才需要无毛刺切换。")
    L.append("    //------------------------------------------------------------")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        cand = cc[cid]
        if len(cand) == 1:
            L.append(f"    // {c.name}: 所有 mode 都用 phy_pclk[{cand[0]}]，直连")
            L.append(f"    assign ctrl_pclk[{cid}] = phy_pclk_out[{cand[0]}];")
        else:
            n = len(cand)
            L.append(f"    // {c.name}: {n} 选 1，候选 "
                     f"{', '.join(f'phy_pclk[{v}]' for v in cand)}")
            L.append(f"    logic [{n-1}:0] pclk_tgt_hold_c{cid};")
            L.append(f"    logic [{n-1}:0] pen_c{cid};")
            L.append(f"    logic [{n-1}:0] pgated_c{cid};")
            L.append(f"    always_ff @(posedge phy_pclk_out[{cand[0]}] "
                     f"or negedge ctrl_rst_n[{cid}])")
            L.append(f"        if (!ctrl_rst_n[{cid}]) pclk_tgt_hold_c{cid} <= "
                     f"{n}'b{1:0{n}b};")
            L.append(f"        else if (|pclk_tgt_c{cid}) pclk_tgt_hold_c{cid} <= "
                     f"pclk_tgt_c{cid};")
            L.append(f"    sel_sync #(.N({n}), .SYNC(1'b1)) u_pclk_sel_sync_c{cid} (")
            L.append(f"        .branch_clk   ({{"
                     + ", ".join(f"phy_pclk_out[{v}]" for v in reversed(cand)) + "}),")
            L.append(f"        .branch_rst_n ({{{n}{{ctrl_rst_n[{cid}]}}}}),")
            L.append(f"        .tgt          (pclk_tgt_hold_c{cid}),")
            L.append(f"        .en           (pen_c{cid})")
            L.append(f"    );")
            for i, v in enumerate(cand):
                L.append(f"    clk_gate u_pclk_gate_c{cid}_b{i} ("
                         f".clk_in(phy_pclk_out[{v}]), .en(pen_c{cid}[{i}]), "
                         f".test_en(test_en), .clk_out(pgated_c{cid}[{i}]));")
            L.append(f"    assign ctrl_pclk[{cid}] = |pgated_c{cid};")
        L.append("")

    # 反馈时钟
    L.append("    //------------------------------------------------------------")
    L.append("    // 反馈时钟：每条 lane 的 pclk_in 接它当前 owner 的 ctrl_pclk。")
    L.append("    // 与数据共用同一组 en，保证数据与时钟同步切换。")
    L.append("    //------------------------------------------------------------")
    for g in cfg.groups:
        if g.is_direct:
            c = g.cands[0]
            for l in g.lanes:
                L.append(f"    assign phy_pclk_in[{l}] = ctrl_pclk[{c}];"
                         f"  // G{g.gid} 直连 {cfg.controllers[c].name}")
        else:
            names = ", ".join(cfg.controllers[c].name for c in g.cands)
            L.append(f"    // G{g.gid} lane{g.lanes[0]}~{g.lanes[-1]}: {names}")
            L.append(f"    logic [{g.n-1}:0] pin_gated_g{g.gid};")
            # 同组共享一组 clk_gate，只算一次 pclk_in_gN 中间信号。
            # 每条 lane 从该中间信号赋值，而不是彼此引用 —— phy_pclk_in
            # 是顶层输出，lane 之间互引会被判成输出端口自环（UNOPTFLAT）。
            L.append(f"    logic pclk_in_g{g.gid};")
            for i, c in enumerate(g.cands):
                L.append(f"    clk_gate u_pin_gate_g{g.gid}_b{i} ("
                         f".clk_in(ctrl_pclk[{c}]), .en(sel_tgt.g{g.gid}[{i}]), "
                         f".test_en(test_en), .clk_out(pin_gated_g{g.gid}[{i}]));")
            L.append(f"    assign pclk_in_g{g.gid} = |pin_gated_g{g.gid};")
            for l in g.lanes:
                L.append(f"    assign phy_pclk_in[{l}] = pclk_in_g{g.gid};")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 反馈复位 mux 子模块

def gen_rst_mux(cfg):
    """每条 lane 的 phy_rst_n 接它当前 owner 的 ctrl_rst_n。

    输入端口仍叫 sel_tgt，但顶层接的是 pipe_lane_sel_gen 的 dec_tgt
    （译码器原始、未经 sel_sync 同步的目标），不是 sel_gen 对外的最终
    sel_tgt。让新 owner 的复位控制随 mode 立即变化，不必等 sel_sync
    走完跨时钟域同步和 break-before-make 的窗口。
    """
    LC, NC = cfg.lane_count, cfg.num_ctrl

    L = [BANNER, "//",
         "// PIPE lane mapper 反馈复位 mux 子模块。",
         "// 每条 lane 的 phy_rst_n 接它当前 owner 的 ctrl_rst_n。",
         "// 输入端口名为 sel_tgt，但顶层实际接的是 pipe_lane_sel_gen 的",
         "// dec_tgt（译码器原始、未经 sel_sync 同步的目标），不是 sel_gen",
         "// 对外的最终 sel_tgt —— 复位跟随 mode 直接变化，不等 sel_sync。",
         "// 复用 onehot_mux 的极性归一化：sel_tgt 全 0（交接窗口，",
         "// 无 owner）时安全态是保持复位（0），而不是悬空或维持上一个 owner。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_rst_mux #(",
         f"    parameter int LANE_COUNT = {LC},",
         f"    parameter int NUM_CTRL   = {NC}",
         ") (",
         "    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,",
         "    input  lane_sel_t              sel_tgt,",
         "    output logic [LANE_COUNT-1:0] phy_rst_n",
         ");",
         ""]

    for g in cfg.groups:
        if g.is_direct:
            c = g.cands[0]
            for l in g.lanes:
                L.append(f"    assign phy_rst_n[{l}] = ctrl_rst_n[{c}];"
                         f"  // G{g.gid} 直连 {cfg.controllers[c].name}")
        else:
            names = ", ".join(cfg.controllers[c].name for c in g.cands)
            L.append(f"    // G{g.gid} lane{g.lanes[0]}~{g.lanes[-1]}: {names}")
            L.append(f"    logic rst_n_g{g.gid};")
            L.append(f"    onehot_mux #(.WIDTH(1), .N({g.n}), .SAFE(1'b0)) u_rst_g{g.gid} (")
            L.append(f"        .sel  (sel_tgt.g{g.gid}),")
            L.append(f"        .din  ({{"
                     + ", ".join(f"ctrl_rst_n[{c}]" for c in reversed(g.cands)) + "}),")
            L.append(f"        .dout (rst_n_g{g.gid})")
            L.append(f"    );")
            for l in g.lanes:
                L.append(f"    assign phy_rst_n[{l}] = rst_n_g{g.gid};")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- MAC->PHY 数据

def gen_data_m2p(cfg):
    """mac2phy 方向数据 mux。"""
    LC = cfg.lane_count
    L = [BANNER, "//",
         "// PIPE lane mapper MAC->PHY 数据 mux。",
         "// onehot_mux 内部做极性归一化，sel 全 0 时输出 SAFE_M2P。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_data_m2p #(",
         f"    parameter int LANE_COUNT = {LC}",
         ") (",
         "    input  lane_sel_t              sel_tgt,",
         "    output mac2phy_lane_t [LANE_COUNT-1:0] phy_mac2phy,"]
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    input  mac2phy_lane_t [{c.max_width-1}:0] {c.lname}_mac2phy,")
    L[-1] = L[-1].rstrip(",")
    L.append(");")
    L.append("")

    for g in cfg.groups:
        for l in g.lanes:
            if g.is_direct:
                c = g.cands[0]
                cl = cfg.mapping[cfg.modes[0]][l][1]
                L.append(f"    assign phy_mac2phy[{l}] = "
                         f"{cfg.controllers[c].lname}_mac2phy[{cl}];  // 直连")
            else:
                srcs = []
                for c in g.cands:
                    m = next(mm for mm in cfg.modes if g.owners[mm] == c)
                    cl = cfg.mapping[m][l][1]
                    srcs.append(f"{cfg.controllers[c].lname}_mac2phy[{cl}]")
                L.append(f"    onehot_mux #(.WIDTH($bits(mac2phy_lane_t)), "
                         f".N({g.n}), .SAFE(SAFE_M2P)) u_m2p_l{l} (")
                L.append(f"        .sel  (sel_tgt.g{g.gid}),")
                L.append(f"        .din  ({{" + ", ".join(reversed(srcs)) + "}),")
                L.append(f"        .dout (phy_mac2phy[{l}])")
                L.append(f"    );")
    L.append("")
    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- PHY->MAC 数据

def gen_data_p2m(cfg):
    """phy2mac 方向数据 mux（按 controller 端口汇聚）。"""
    LC = cfg.lane_count
    L = [BANNER, "//",
         "// PIPE lane mapper PHY->MAC 数据 mux（按 controller 端口汇聚）。",
         "// sel_tgt 的互斥性由 sel_sync 保证。未被驱动的端口 tie 安全态。",
         "import pipe_pkg::*;",
         "",
         f"module pipe_lane_data_p2m #(",
         f"    parameter int LANE_COUNT = {LC}",
         ") (",
         "    input  lane_sel_t              sel_tgt,",
         "    input  phy2mac_lane_t [LANE_COUNT-1:0] phy_phy2mac,"]
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    output phy2mac_lane_t [{c.max_width-1}:0] {c.lname}_phy2mac,")
    L[-1] = L[-1].rstrip(",")
    L.append(");")
    L.append("")

    port_src = {}
    for m in cfg.modes:
        for l in range(LC):
            cid, cl = cfg.mapping[m][l]
            g = cfg.group_of_lane(l)
            b = 0 if g.is_direct else g.branch_of(cid)
            port_src.setdefault((cid, cl), set()).add((l, g.gid, b))
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    // {c.name} x{c.max_width}")
        for cl in range(c.max_width):
            srcs = sorted(port_src.get((cid, cl), set()))
            if not srcs:
                L.append(f"    assign {c.lname}_phy2mac[{cl}] = SAFE_P2M;"
                         f"  // 所有 mode 下都未被驱动")
                continue
            if len(srcs) == 1 and cfg.groups[srcs[0][1]].is_direct:
                l = srcs[0][0]
                L.append(f"    assign {c.lname}_phy2mac[{cl}] = phy_phy2mac[{l}];"
                         f"  // 直连 lane{l}")
                continue
            gid = srcs[0][1]
            g = cfg.groups[gid]
            din = []
            for i in range(g.n):
                hit = [s for s in srcs if s[2] == i]
                if hit:
                    din.append(f"phy_phy2mac[{hit[0][0]}]")
                else:
                    din.append("SAFE_P2M")
            L.append(f"    onehot_mux #(.WIDTH($bits(phy2mac_lane_t)), "
                     f".N({g.n}), .SAFE(SAFE_P2M)) u_p2m_{c.lname}_{cl} (")
            L.append(f"        .sel  (sel_tgt.g{gid}),")
            L.append(f"        .din  ({{" + ", ".join(reversed(din)) + "}),")
            L.append(f"        .dout ({c.lname}_phy2mac[{cl}])")
            L.append(f"    );")
        L.append("")

    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- 顶层

def gen_top(cfg):
    nm = len(cfg.modes)
    LC, NC = cfg.lane_count, cfg.num_ctrl

    L = [BANNER, "//"]
    L.append("// PIPE lane mapper 顶层。")
    L.append("//")
    L.append("// 纯例化层：")
    L.append("//   pipe_lane_sel_gen  -- mode 译码 + group sel_sync，产生 sel_tgt")
    L.append("//   pipe_lane_clk_mux  -- controller pclk 生成 + 反馈时钟 mux")
    L.append("//   pipe_lane_rst_mux  -- 反馈复位 mux")
    L.append("//   pipe_lane_data_m2p -- MAC->PHY 数据 mux")
    L.append("//   pipe_lane_data_p2m -- PHY->MAC 数据 mux")
    L.append("//")
    L.append("// lane 分组：归属序列相同的 lane 自动成组，共享一个 BBM。")
    L.append("//")
    for g in cfg.groups:
        rng = f"lane{g.lanes[0]}~{g.lanes[-1]}" if len(g.lanes) > 1 else f"lane{g.lanes[0]}"
        owners = " / ".join(cfg.controllers[g.owners[m]].name for m in cfg.modes)
        kind = "直连" if g.is_direct else f"{g.n} 选 1 BBM"
        L.append(f"//   G{g.gid} {rng:<14} {owners:<24} {kind}")
    L.append("import pipe_pkg::*;")
    L.append("")
    L.append("module pipe_lane_mapper_top #(")
    L.append(f"    parameter int NUM_MODES  = {nm},")
    L.append(f"    parameter int LANE_COUNT = {LC},")
    L.append(f"    parameter int NUM_CTRL   = {NC}")
    L.append(") (")
    L.append("    /* verilator lint_off UNUSEDSIGNAL */")
    L.append("    input  logic [LANE_COUNT-1:0] phy_pclk_out,")
    L.append("    /* verilator lint_on UNUSEDSIGNAL */")
    L.append("    input  logic                  test_en,")
    L.append("    input  logic [NUM_CTRL-1:0]   ctrl_rst_n,   // 每 controller 一根，外部已同步")
    L.append("    input  logic [$clog2(NUM_MODES)-1:0] mode,")
    L.append("")
    L.append("    output logic [NUM_CTRL-1:0]   ctrl_pclk,")
    L.append("    output logic [LANE_COUNT-1:0] phy_pclk_in,")
    L.append("    output logic [LANE_COUNT-1:0] phy_rst_n,")
    L.append("")
    L.append("    // PHY 侧 PIPE 数据")
    L.append("    output mac2phy_lane_t [LANE_COUNT-1:0] phy_mac2phy,")
    L.append("    input  phy2mac_lane_t [LANE_COUNT-1:0] phy_phy2mac,")
    L.append("")
    L.append("    // Controller 侧，各自真实宽度")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"    // {c.name} x{c.max_width}")
        L.append(f"    input  mac2phy_lane_t [{c.max_width-1}:0] {c.lname}_mac2phy,")
        L.append(f"    output phy2mac_lane_t [{c.max_width-1}:0] {c.lname}_phy2mac,")
    L[-1] = L[-1].rstrip(",")
    L.append(");")
    L.append("")

    cc = cfg.ctrl_pclk_cands()
    muxed_c = [c for c in sorted(cfg.controllers) if len(cc[c]) > 1]

    # ---- 内部连线
    L.append("    lane_sel_t sel_tgt;   // 各 group 当前实际生效的 owner 选择（sel_sync 同步后）")
    L.append("    lane_sel_t dec_tgt;   // 各 group 译码器的原始选择（未同步），给 rst_mux 用")
    for c in muxed_c:
        L.append(f"    logic [{len(cc[c])-1}:0] pclk_tgt_c{c};"
                 f"   // {cfg.controllers[c].name} 的 pclk 候选目标")
    L.append("")

    # ---- 选择生成子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // 选择生成子模块：mode 译码 + group sel_sync，产生 sel_tgt / dec_tgt")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_sel_gen #(")
    L.append("        .NUM_MODES (NUM_MODES),")
    L.append("        .NUM_CTRL  (NUM_CTRL)")
    L.append("    ) u_sel_gen (")
    L.append("        .mode       (mode),")
    L.append("        .ctrl_pclk  (ctrl_pclk),")
    L.append("        .ctrl_rst_n (ctrl_rst_n),")
    L.append("        .sel_tgt    (sel_tgt),")
    L.append("        .dec_tgt    (dec_tgt)" + ("," if muxed_c else ""))
    for i, c in enumerate(muxed_c):
        tail = "," if i != len(muxed_c) - 1 else ""
        L.append(f"        .pclk_tgt_c{c} (pclk_tgt_c{c}){tail}")
    L.append("    );")
    L.append("")

    # ---- 时钟 mux 子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // 时钟 mux 子模块：ctrl_pclk 生成 + 反馈时钟 mux")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_clk_mux #(")
    L.append("        .LANE_COUNT (LANE_COUNT),")
    L.append("        .NUM_CTRL   (NUM_CTRL)")
    L.append("    ) u_clk_mux (")
    L.append("        .phy_pclk_out (phy_pclk_out),")
    L.append("        .test_en      (test_en),")
    L.append("        .ctrl_rst_n   (ctrl_rst_n),")
    for c in muxed_c:
        L.append(f"        .pclk_tgt_c{c} (pclk_tgt_c{c}),")
    L.append("        .sel_tgt      (sel_tgt),")
    L.append("        .ctrl_pclk    (ctrl_pclk),")
    L.append("        .phy_pclk_in  (phy_pclk_in)")
    L.append("    );")
    L.append("")

    # ---- 反馈复位 mux 子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // 反馈复位 mux 子模块：phy_rst_n 按当前 owner 选 ctrl_rst_n")
    L.append("    // 用 dec_tgt（译码器原始输出，未经 sel_sync 同步），不用 sel_tgt")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_rst_mux #(")
    L.append("        .LANE_COUNT (LANE_COUNT),")
    L.append("        .NUM_CTRL   (NUM_CTRL)")
    L.append("    ) u_rst_mux (")
    L.append("        .ctrl_rst_n (ctrl_rst_n),")
    L.append("        .sel_tgt    (dec_tgt),")
    L.append("        .phy_rst_n  (phy_rst_n)")
    L.append("    );")
    L.append("")

    # ---- MAC->PHY 数据子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // MAC->PHY 数据 mux")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_data_m2p #(")
    L.append("        .LANE_COUNT (LANE_COUNT)")
    L.append("    ) u_data_m2p (")
    L.append("        .sel_tgt      (sel_tgt),")
    L.append("        .phy_mac2phy  (phy_mac2phy),")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"        .{c.lname}_mac2phy ({c.lname}_mac2phy),")
    L[-1] = L[-1].rstrip(",")
    L.append("    );")
    L.append("")

    # ---- PHY->MAC 数据子模块
    L.append("    //------------------------------------------------------------")
    L.append("    // PHY->MAC 数据 mux")
    L.append("    //------------------------------------------------------------")
    L.append("    pipe_lane_data_p2m #(")
    L.append("        .LANE_COUNT (LANE_COUNT)")
    L.append("    ) u_data_p2m (")
    L.append("        .sel_tgt      (sel_tgt),")
    L.append("        .phy_phy2mac  (phy_phy2mac),")
    for cid in sorted(cfg.controllers):
        c = cfg.controllers[cid]
        L.append(f"        .{c.lname}_phy2mac ({c.lname}_phy2mac),")
    L[-1] = L[-1].rstrip(",")
    L.append("    );")
    L.append("")

    L.append("endmodule")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- filelist

def gen_filelist(cfg, common_rel):
    """<集>/rtl/flist.f。路径相对 flist.f 自身所在目录解析。

    common 是手写公共模块，固定在 script/common/ 下，多个配置集共用；
    flist.f 里用相对路径指过去（由调用方按集的位置算好）。
    """
    common = ["sync2.sv", "sel_sync.sv", "clk_gate.sv", "onehot_mux.sv"]
    gen = [
        "pipe_pkg.sv",
        "pipe_lane_decoder.sv",
        "pipe_lane_sel_gen.sv",
        "pipe_lane_clk_mux.sv",
        "pipe_lane_rst_mux.sv",
        "pipe_lane_data_m2p.sv",
        "pipe_lane_data_p2m.sv",
        "pipe_lane_mapper_top.sv",
    ]
    L = [BANNER,
         "// RTL filelist。package 必须排在使用它的模块之前。",
         "",
         f"+incdir+{common_rel}",
         "+incdir+src",
         ""]
    for f in common:
        L.append(f"{common_rel}/{f}")
    L.append("")
    for f in gen:
        L.append(f"src/{f}")
    return "\n".join(L) + "\n"


def gen_sim_filelist(cfg, flist_rel):
    """tb/sim.f。路径相对 sim.f 自身所在目录（tb/）解析。

    flist_rel 是从 tb/ 指向本次生成集 rtl/flist.f 的相对路径。

    嵌套引用 flist.f 必须用 -F（而不是 -f）：Verilator 的 -f 把文件内的
    相对路径当成相对「调用时的当前目录」解析，两层 -f 嵌套时内层路径会
    按外层调用者的 cwd 解析，而不是按 flist.f 自己所在的 rtl/ 目录，从
    不同目录调用就会找不到文件。-F 则是相对「该参数文件自身所在目录」
    解析，嵌套后各自独立，才能保证从项目根目录或从 tb/ 下调用都一样能跑。
    """
    L = [BANNER,
         "// 仿真 filelist：RTL + testbench。",
         "",
         f"-F {flist_rel}",
         "",
         "tb_pipe_lane_mapper.sv"]
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description="生成 PIPE lane mapper RTL")
    ap.add_argument("--config", default=None, metavar="SET",
                    help="配置集目录。CSV 依次在 <SET>/config/、<SET>/ 本身、"
                         "内置 script/config/ 下查找；生成物固定输出到 "
                         "<SET>/rtl/。默认为 <plm根>/config")
    ap.add_argument("--tb-dir", default=str(PLM_ROOT / "tb"))
    ap.add_argument("--sel-mode", choices=["sync", "comb"], default="sync",
                    help="group 的 sel_sync 模块用哪种 SYNC 参数：sync=SYNC=1"
                         "（默认，break-before-make + 两级同步器，跨时钟域安全）；"
                         "comb=SYNC=0（组合直通，仅当候选 controller 共用同一"
                         "时钟域时安全）")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()

    csv_dir, out_rtl = resolve_set(a.config)
    cfg = load(csv_dir)
    src = out_rtl / "src"
    src.mkdir(parents=True, exist_ok=True)
    tb_dir = Path(a.tb_dir)
    tb_dir.mkdir(parents=True, exist_ok=True)

    # flist.f 引用公共模块、sim.f 引用 flist.f，都用相对路径写死进文件，
    # 生成时按集的实际位置算，保证从任意目录调用都成立。
    common_rel = Path(os.path.relpath(COMMON_DIR, out_rtl)).as_posix()
    flist_rel = Path(os.path.relpath(out_rtl / "flist.f", tb_dir)).as_posix()

    print(f"配置: {csv_dir}")
    print(f"输出: {out_rtl}")
    files = {
        src / "pipe_pkg.sv": gen_pkg(cfg),
        src / "pipe_lane_decoder.sv": gen_decoder(cfg),
        src / "pipe_lane_sel_gen.sv": gen_sel_gen(cfg, a.sel_mode),
        src / "pipe_lane_clk_mux.sv": gen_clk_mux(cfg),
        src / "pipe_lane_rst_mux.sv": gen_rst_mux(cfg),
        src / "pipe_lane_data_m2p.sv": gen_data_m2p(cfg),
        src / "pipe_lane_data_p2m.sv": gen_data_p2m(cfg),
        src / "pipe_lane_mapper_top.sv": gen_top(cfg),
        out_rtl / "flist.f": gen_filelist(cfg, common_rel),
        tb_dir / "sim.f": gen_sim_filelist(cfg, flist_rel),
    }
    for p, c in files.items():
        p.write_text(c)
        print(f"  生成 {p}")

    if not a.quiet:
        print()
        print(cfg.report())


if __name__ == "__main__":
    main()