// Auto-generated by tool/plm_gen.py -- DO NOT EDIT
//
// mode decoding: produces each lane group's target owner, and each
// controller's target pclk source. Purely combinational, no state.
//
// Output feeds directly into BBM's tgt port; BBM handles cross-domain
// synchronization and interlocking.
import pipe_pkg::*;

module pipe_lane_mode_dec #(
    parameter int NUM_MODES = 2,
    /* verilator lint_off UNUSEDPARAM */
    parameter int NUM_CTRL  = 2   // only used by controllers with more than one candidate
    /* verilator lint_on UNUSEDPARAM */
) (
    input  logic [$clog2(NUM_MODES)-1:0] mode,
    output lane_sel_t sel_tgt
);

    always_comb begin
        sel_tgt = '0;

        unique case (mode)
            0: begin
                sel_tgt.g1 = 2'b01;  // PCIe_x4
            end
            1: begin
                sel_tgt.g1 = 2'b10;  // USB_x2
            end
            default: begin
                sel_tgt = '0;
            end
        endcase
    end

endmodule
