// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
// RTL filelist。package 必须排在使用它的模块之前。

+incdir+${PLM_ROOT}/rtl/common
+incdir+${PLM_ROOT}/rtl/gen

${PLM_ROOT}/rtl/common/sync2.sv
${PLM_ROOT}/rtl/common/bbm_sel_onehot.sv
${PLM_ROOT}/rtl/common/clk_gate.sv
${PLM_ROOT}/rtl/common/onehot_mux.sv

${PLM_ROOT}/rtl/gen/pipe_pkg.sv
${PLM_ROOT}/rtl/gen/pipe_lane_decoder.sv
${PLM_ROOT}/rtl/gen/pipe_lane_clk_top.sv
${PLM_ROOT}/rtl/gen/pipe_lane_data_m2p.sv
${PLM_ROOT}/rtl/gen/pipe_lane_data_p2m.sv
${PLM_ROOT}/rtl/gen/pipe_lane_mapper_top.sv
