// Auto-generated by tools/plm_gen.py -- DO NOT EDIT
// RTL filelist。package 必须排在使用它的模块之前。

+incdir+common
+incdir+src

common/sync2.sv
common/sel_sync.sv
common/clk_gate.sv
common/onehot_mux.sv

src/pipe_pkg.sv
src/pipe_lane_decoder.sv
src/pipe_lane_clk_top.sv
src/pipe_lane_rst_top.sv
src/pipe_lane_data_m2p.sv
src/pipe_lane_data_p2m.sv
src/pipe_lane_mapper_top.sv
